name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' 
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: ./asistenciacontrol
        run: flutter pub get

      - name: Analyze code
        working-directory: ./asistenciacontrol
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Run tests
        working-directory: ./asistenciacontrol 
        run: flutter test
